- ignore: {name: "Avoid lambda"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Redundant lambda"}
- ignore: {name: "Use ++"}
- ignore: {name: "Use camelCase"}
