name: &this tldr-client
version: !include ./version.json
synopsis: |
  Client for tldr-pages
description: |
  Client for [tldr-pages](https://tldr.sh/).

  See [GitHub README](https://github.com/trskop/tldr-client#readme) for more
  information.

github: trskop/tldr-client
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2021 Peter Trško
category: Command Line Tools, Tools

flags:
  static:
    description: Build static executables
    manual: true
    default: false

extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >=4.13 && <5
  # ^ Version 4.13.0.0 is bundled with 8.8.1

ghc-options:
  - "-Wall"
  - "-Wcompat"
  - "-Wimplicit-prelude"
  - "-Wincomplete-record-updates"
  - "-Wpartial-fields"
  - "-Wmissing-deriving-strategies" # GHC >8.8
  - "-Wredundant-record-wildcards" # GHC >8.10
  - "-Wunused-packages" # GHC >8.10
  - "-Wunused-record-wildcards" # GHC >8.10

executables:
  tldr:
    source-dirs: app
    main: Main.hs
    dependencies:
      - aeson >=1.5.2.0 && <2
      - dhall >=1.39.0 && <2
      - country-codes >=0.1.4 && <1
      - case-insensitive >=1.2 && <2
      - directory
      - either >=5.0.1.1 && <6
      - filepath
      - iso639 >=0.1.0.3 && <1
      # ^ Language codes
      - lens
      - optparse-applicative >=0.15.1.0 && <1
      - prettyprinter >=1.7.0 && <2
      - prettyprinter-ansi-terminal
      - temporary >=1.3 && <2
      # ^ Version 1.3 is the first one that uses random hex string in temp
      # names instead of PIDs.
      - text >=1.2.4.0 && <2
      - tldr >=0.9.1 && <1
      # ^ Fucntion `renderPage` takes `ColorSetting` argument since version
      # 0.9.1.
      - tldr >=0.9.1 && <1
      - transformers
      - verbosity >=0.3 && <1
      - wreq >=0.5.3.2 && <1
      # ^ Version 0.8.3.2 is first to handle http-client >=0.6.0
      - zip-archive >=0.4 && <1

      # Not on Hackage:
      - mainplate

      # Most min version bounds were taken from LTS-16.28 that was used during
      # initial development.
      #- async >=2.2.2 && <3
      #- bytestring >=0.10.10.1 && <1

    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -static
          - -O2
          - -fPIC
        cpp-options:
          - -DSTATIC_EXECUTABLE
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread
