name: &this tldr-client
version: !include ./version.json
synopsis: |
  Client for tldr-pages
description: |
  Client for [tldr-pages](https://tldr.sh/).

  See [GitHub README](https://github.com/trskop/tldr-client#readme) for more
  information.

github: trskop/tldr-client
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2021-2024 Peter Trško
category: Command Line Tools, Tools

flags:
  static:
    description: Build static executables
    manual: true
    default: false

  pedantic:
    description: Turn on additional warning flags
    manual: true
    default: false

extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost # GHC ≥8.10
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedRecordDot # GHC ≥9.2
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >=4.13 && <5
  # ^ Version 4.13.0.0 is bundled with 8.8.1

# All the dependencies that we use with version bounds. This keeps them all
# consistent by the virtue of sharing.
_dependencies:
  - &aeson                       "aeson >=2 && <3"
  - &bytestring                  "bytestring >=0.10 && <1"
  - &case-insensitive            "case-insensitive >=1.2 && <2"
  - &dhall                       "dhall >=1.41.2 && <2"
  - &directory                   "directory >=1.3.5 && <2"
  - &either                      "either >=5.0.1.1 && <6"
  - &filepath                    "filepath >=1.4.2.1 && <2"
  # ^ Version 1.4.2.1 is bundled with GHC 8.6.1 and later.
  - &iso639                      "iso639 >=0.1.0.3 && <1"
  # ^ Language codes
  - &lens                        "lens >=4.19 && <6"
  # ^ Version 5.* is supported as well.
  - &mtl                         "mtl >=2.2.2 && <3"
  - &optparse-applicative        "optparse-applicative >=0.15.1.0 && <1"
  - &prettyprinter               "prettyprinter >=1.7.0 && <2"
  - &prettyprinter-ansi-terminal "prettyprinter-ansi-terminal"
  - &safe                        "safe >=0.3.19 && <1"
  - &sqlite-simple               "sqlite-simple >=0.4.16 && <1"
  - &temporary                   "temporary >=1.3 && <2"
  # ^ Version 1.3 is the first one that uses random hex string in temp
  # names instead of PIDs.
  - &terminal-size               "terminal-size >=0.3.2.1 && <1"
  - &terminfo                    "terminfo >=0.4.1.4 && <1"
  - &text                        "text >=1.2.4.0 && <3"
  - &tldr                        "tldr >=0.9.1 && <1"
  # ^ Fucntion `renderPage` takes `ColorSetting` argument since version
  # 0.9.1.
  - &transformers                "transformers >=0.5.6 && <1"
  # Version 0.5.6 introduced CPS variant of WriterT.
  - &verbosity                   "verbosity >=0.3 && <1"
  - &wreq                        "wreq >=0.5.3.2 && <1"
  # ^ Version 0.8.3.2 is first to handle http-client >=0.6.0
  - &zip-archive                 "zip-archive >=0.4 && <1"

  # Testing
  - &call-stack                  "call-stack >=0.2.0 && <1"
  - &tasty                       "tasty >=1.2.3 && <2"
  - &tasty-hunit                 "tasty-hunit >=0.10.0.2 && <1"
  - &tasty-quickcheck            "tasty-quickcheck"
  - &unordered-containers        "unordered-containers >=0.2.15 && <1"

  # Not on Hackage:
  - &mainplate mainplate

ghc-options:
  - "-Wall"
  - "-Wcompat"
  - "-Wimplicit-prelude"
  - "-Wincomplete-record-updates"
  - "-Wpartial-fields"
  - "-Wmissing-deriving-strategies" # GHC >8.8
  - "-Wredundant-record-wildcards" # GHC >8.10
  - "-Wunused-packages" # GHC >8.10
  - "-Wunused-record-wildcards" # GHC >8.10

when:
  - condition: flag(pedantic)
    ghc-options:
      # Auto-generated files do not turn off this warning locally and it cannot
      # be fixed easily.
      - "-Wprepositive-qualified-module" # GHC >8.10

library:
  source-dirs: src

  dependencies:
      - *aeson
      - *bytestring
      - *case-insensitive
      - *dhall
      - *directory
      - *either
      - *filepath
      - *iso639
      - *lens
      - *mainplate
      - *mtl
      - *optparse-applicative
      - *prettyprinter
      - *prettyprinter-ansi-terminal
      - *safe
      - *sqlite-simple
      - *temporary
      - *terminal-size
      - *terminfo
      - *text
      - *tldr
      - *verbosity
      - *wreq
      - *zip-archive

  when:
    - condition: flag(static)
      ghc-options:
        - -static
        - -O2
        - -fPIC

executables:
  tldr:
    source-dirs: app
    main: Main.hs
    dependencies:
      - *this

      - *directory
      - *mainplate
      - *text
      - *verbosity

    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -static
          - -O2
          - -fPIC
        cpp-options:
          - -DSTATIC_EXECUTABLE
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread

  command-wrapper-tldr:
    source-dirs: app-subcommand
    main: Main.hs
    dependencies:
      - *this

      - *case-insensitive
      - *directory
      - *filepath
      - *mainplate
      - *mtl
      - *text
      - *verbosity

    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -static
          - -O2
          - -fPIC
        cpp-options:
          - -DSTATIC_EXECUTABLE
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread

tests:
  tldr-client-unit-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
      - *this

      - *call-stack
      - *tasty
      - *tasty-hunit
      - *unordered-containers

      # Same dependencies as the library:
      - *mainplate
      - *text

    ghc-options: ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
