# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# GHC 9.4.8
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml

packages:
  - '.'

extra-deps:
  - tldr-0.9.2
  - cmark-0.6.1

    # Dependency of mainplate:
  - git: https://github.com/trskop/host-and-port.git
    commit: 2e216dd7fc86d4c952291694af55f5d3632b79f6

  - git: https://github.com/trskop/mainplate.git
    commit: 54e432e1b5b6266816e3591cfef7da6d498b99f4

allow-newer: false

flags:
  tldr-client:
    pedantic: true
